name: Mise à jour horaire

on:
  schedule:
    # Exécute toutes les heures, à la 0ème minute de chaque heure (UTC).
    - cron: '0 * * * *' 

  workflow_dispatch:

jobs:
  update_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: design-minimaliste # Cible la branche design-minimaliste
          fetch-depth: 0 

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.1' 
          bundler-cache: true 

      - name: Run Instapaper script
        run: ruby scripts/fetch_instapaper.rb
        env:
          INSTAPAPER_HOME_RSS: ${{ secrets.INSTAPAPER_HOME_RSS }}
          INSTAPAPER_TAG_TECH: ${{ secrets.INSTAPAPER_TAG_TECH }}
          INSTAPAPER_TAG_SANTE: ${{ secrets.INSTAPAPER_TAG_SANTE }}

      - name: Commit all content changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions Bot"
          git add _data/ categories/ 
          git commit -m "Automatisation: Mise à jour horaire du contenu du site" || echo "No content changes to commit"
          git push origin design-minimaliste
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_ROOT_USER }}
          password: ${{ secrets.FTP_ROOT_PASSWORD }}
          local-dir: ./_site/
          server-dir: ./
          state-name: .ftp-deploy-state
          protocol: ftp
          exclude: |
            .git/
            .github/
            .jekyll-cache/
