name: Mise à jour journalière (Semaine uniquement)

on:
  schedule:
    # 0 = Minute, 14 = Heure (UTC), * = Jour, * = Mois, 1-5 = Lundi au Vendredi
    - cron: '0 14 * * 1-5' 

  workflow_dispatch: # Permet de lancer la mise à jour manuellement

jobs:
  ping-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/6a049c6c5a5eb6a6785dd85b"