name: Mise à jour quotidienne du site

on:
  schedule:
    # Mise à jour quotidienne à 23h00 (UTC) du lundi au vendredi
   - cron: '0 23 * * *'

  workflow_dispatch: # Permet de lancer la mise à jour manuellement

jobs:
  ping-netlify:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build
        run: curl -X POST -d {} "https://api.netlify.com/build_hooks/6a049c6c5a5eb6a6785dd85b"
